version: '3.8'
services:
  service:
    build: service
    ports:
      - '5000:5000'
    depends_on:
      - dynamodb-local
    environment:
      # These are not required to be valid AWS keys to access DynamoDB locally
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'

  fetcher:
    build: fetcher
    depends_on:
      - dynamodb-local
    links:
      - dynamodb-local
    environment:
      # These are not required to be valid AWS keys to access DynamoDB locally
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
